# -*- coding: utf-8 -*-
"""gemma.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C5cDZPjHva5oekBU8zbus3NhyLLI1AM_
"""

import os
os.environ["HF_TOKEN"] = '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'
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("google/gemma-7b")
model = AutoModelForCausalLM.from_pretrained("google/gemma-7b")

input_text = "Write me a poem about Machine Learning."
input_ids = tokenizer(input_text, return_tensors="pt")

outputs = model.generate(**input_ids)
print(tokenizer.decode(outputs[0]))

!pip install -qU "transformers == 4.38.0" --upgrade

!git remote set-url origin https://martavn16:HF_TOKEN@huggingface.co/google/gemma-7b
!git pull origin

from google.colab import userdata
.userdata.get('HF_TOKEN')

!git lfs install

!git clone https://martavn16:HF_TOKEN@huggingface.co/google/gemma-7b

from transformers import AutoTokenizer
model = "google/gemma-7b"
tokenizer = AutoTokenizer.from_pretrained(model)