# -*- coding: utf-8 -*-
"""GEMMA_FUNCIONAL.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ip0VOcZt_44AqrXT1S1CcwPAN5kuyCtR
"""

import os
from google.colab import userdata

# Note: `userdata.get` is a Colab API. If you're not using Colab, set the env
# vars as appropriate for your system.
os.environ["KAGGLE_USERNAME"] = userdata.get('KAGGLE_USERNAME')
os.environ["KAGGLE_KEY"] = userdata.get('KAGGLE_KEY')

# Install Keras 3 last. See https://keras.io/getting_started/ for more details.
!pip install -q -U keras-nlp

!pip install keras==2.15.0

!myenv\Scripts\activate     # Para Windows
!pip install tensorflow==2.15.0
!pip install keras==2.15.0

!pip install -q -U keras>=3

!pip install -q --upgrade keras
!pip install -q --upgrade keras-nlp

import keras
import keras_nlp

import os

os.environ["KERAS_BACKEND"] = "jax"  # Or "tensorflow" or "torch".

gemma_lm = keras_nlp.models.GemmaCausalLM.from_preset("gemma_2b_en")

print(gemma_lm.generate("What is the meaning of life?", max_length=64))